# Generated by Django 3.2.9 on 2021-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название группы')),
                ('description', models.JSONField(null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.JSONField(null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
