# Generated by Django 3.2.9 on 2021-11-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0002_auto_20211121_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
    ]
