# Generated by Django 3.2.9 on 2021-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0004_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_slug',
            field=models.SlugField(default='def'),
            preserve_default=False,
        ),
    ]
