# Generated by Django 3.2.9 on 2021-12-02 17:35

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0006_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.CharField(default='etu', max_length=150, verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='specialization',
            field=models.CharField(default='none', max_length=150, verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_slug',
            field=slugger.fields.AutoSlugField(max_length=150, populate_from='name', unique=True, verbose_name='URL'),
        ),
    ]
