# Generated by Django 3.2.9 on 2021-12-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0007_auto_20211202_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Неделя')),
                ('order', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=15, verbose_name='День недели')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.lesson')),
                ('week_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.weektemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='LessonFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.lessontime'),
        ),
    ]
