# Generated by Django 3.2.9 on 2021-12-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0009_alter_lessonformat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystudy_app.lessonformat'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystudy_app.lessontime'),
        ),
    ]
