# Generated by Django 3.2.9 on 2021-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0010_auto_20211218_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
