# Generated by Django 3.2.9 on 2021-12-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0011_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало обучения'),
        ),
    ]
