# Generated by Django 3.2.9 on 2021-12-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0012_group_schedule_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
