# Generated by Django 3.2.9 on 2021-12-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0013_auto_20211218_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='discipline',
            field=models.CharField(default='ОУП', max_length=100),
            preserve_default=False,
        ),
    ]
