# Generated by Django 3.2.9 on 2021-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0014_lesson_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
