# Generated by Django 3.2.9 on 2021-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0016_alter_lesson_lesson_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_template',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(default='template', max_length=100),
            preserve_default=False,
        ),
    ]
