# Generated by Django 3.2.9 on 2021-12-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0020_auto_20211222_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.group'),
            preserve_default=False,
        ),
    ]
