# Generated by Django 3.2.9 on 2021-12-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0021_tasklabel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
