# Generated by Django 3.2.9 on 2021-12-22 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0023_alter_discipline_label_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklabel',
            name='group',
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystudy_app.discipline')),
                ('tasklabel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystudy_app.tasklabel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
