# Generated by Django 3.2.9 on 2021-12-23 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0025_auto_20211223_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='label_color',
        ),
        migrations.CreateModel(
            name='DisciplineLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystudy_app.disciplinelabel'),
        ),
    ]
