# Generated by Django 3.2.9 on 2021-12-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0026_auto_20211223_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='label',
        ),
        migrations.AddField(
            model_name='disciplinelabel',
            name='discipline',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='mystudy_app.discipline'),
            preserve_default=False,
        ),
    ]
