# Generated by Django 3.2.9 on 2021-12-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0027_auto_20211223_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='discipline',
        ),
        migrations.AddField(
            model_name='task',
            name='discipline_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystudy_app.disciplinelabel'),
        ),
    ]
