# Generated by Django 3.2.9 on 2021-12-24 15:57

from django.db import migrations, models
import mystudy_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0028_auto_20211223_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('adding_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to=mystudy_app.models.user_directory_path)),
            ],
        ),
    ]
