# Generated by Django 3.2.9 on 2021-12-24 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0030_file_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='adding_date',
        ),
        migrations.AddField(
            model_name='file',
            name='adding_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
