# Generated by Django 3.2.9 on 2021-12-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystudy_app', '0035_auto_20211226_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentsGroup',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='students_group',
        ),
    ]
